# Generated by Django 3.1.7 on 2022-02-17 15:44

import apps.MDM.mdm_negocios.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoNegocio', models.CharField(max_length=150, null=True)),
                ('ruc', models.CharField(max_length=13, null=True, unique=True)),
                ('razonSocial', models.CharField(max_length=255, null=True)),
                ('nombreComercial', models.CharField(max_length=255, null=True)),
                ('nacionalidad', models.CharField(max_length=150, null=True)),
                ('fechaCreacionNegocio', models.DateField(max_length=150, null=True)),
                ('edadNegocio', models.SmallIntegerField(null=True)),
                ('paisOrigen', models.CharField(max_length=150, null=True)),
                ('paisResidencia', models.CharField(max_length=150, null=True)),
                ('provinciaResidencia', models.CharField(max_length=150, null=True)),
                ('ciudadResidencia', models.CharField(max_length=150, null=True)),
                ('numeroEmpleados', models.SmallIntegerField(null=True)),
                ('segmentoActividadEconomica', models.CharField(max_length=150, null=True)),
                ('profesion', models.CharField(max_length=255, null=True)),
                ('actividadEconomica', models.CharField(max_length=255, null=True)),
                ('llevarContabilidad', models.SmallIntegerField(default=1)),
                ('ingresosPromedioMensual', models.FloatField(null=True)),
                ('gastosPromedioMensual', models.FloatField(null=True)),
                ('numeroEstablecimientos', models.SmallIntegerField(null=True)),
                ('telefonoOficina', models.CharField(max_length=150, null=True)),
                ('celularOficina', models.CharField(max_length=150, null=True)),
                ('celularPersonal', models.CharField(max_length=150, null=True)),
                ('whatsappPersonal', models.CharField(max_length=150, null=True)),
                ('whatsappSecundario', models.CharField(max_length=150, null=True)),
                ('correoPersonal', models.EmailField(max_length=150, null=True)),
                ('correoOficina', models.EmailField(max_length=150, null=True)),
                ('googlePlus', models.EmailField(max_length=150, null=True)),
                ('twitter', models.CharField(max_length=150, null=True)),
                ('facebook', models.CharField(max_length=150, null=True)),
                ('instagram', models.CharField(max_length=150, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.MDM.mdm_negocios.models.upload_path)),
                ('estado', models.CharField(default='Inactivo', max_length=200)),
                ('empresa_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalNegocios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoContacto', models.CharField(max_length=150, null=True)),
                ('cedula', models.CharField(max_length=10, null=True, unique=True)),
                ('nombres', models.CharField(max_length=150, null=True)),
                ('apellidos', models.CharField(max_length=150, null=True)),
                ('telefonoFijo', models.CharField(max_length=15, null=True)),
                ('extension', models.CharField(max_length=15, null=True)),
                ('celularEmpresa', models.CharField(max_length=15, null=True)),
                ('whatsappEmpresa', models.CharField(max_length=15, null=True)),
                ('celularPersonal', models.CharField(max_length=15, null=True)),
                ('whatsappPersonal', models.CharField(max_length=15, null=True)),
                ('correoEmpresa', models.EmailField(blank=True, max_length=150, null=True)),
                ('correoPersonal', models.EmailField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(default='Inactivo', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mdm_negocios.negocios')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionesEstablecimientosNegocios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDireccion', models.CharField(max_length=150, null=True)),
                ('pais', models.CharField(max_length=150, null=True)),
                ('provincia', models.CharField(max_length=150, null=True)),
                ('ciudad', models.CharField(max_length=150, null=True)),
                ('callePrincipal', models.CharField(max_length=150, null=True)),
                ('numero', models.CharField(max_length=20, null=True)),
                ('calleSecundaria', models.CharField(max_length=150, null=True)),
                ('edificio', models.CharField(max_length=150, null=True)),
                ('piso', models.CharField(max_length=150, null=True)),
                ('oficina', models.CharField(max_length=150, null=True)),
                ('referencia', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mdm_negocios.negocios')),
            ],
        ),
    ]
