# Generated by Django 3.1.7 on 2022-02-23 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negocio', models.SmallIntegerField(null=True)),
                ('cliente', models.SmallIntegerField(null=True)),
                ('numeroFactura', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateField(null=True)),
                ('tipoIdentificacion', models.CharField(max_length=150, null=True)),
                ('identificacion', models.CharField(max_length=13, null=True)),
                ('razonSocial', models.CharField(max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=150, null=True)),
                ('correo', models.EmailField(max_length=255, null=True)),
                ('nombreVendedor', models.CharField(max_length=255, null=True)),
                ('subTotal', models.FloatField(null=True)),
                ('descuento', models.FloatField(null=True)),
                ('iva', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('canal', models.CharField(max_length=255, null=True)),
                ('numeroProductosComprados', models.IntegerField(null=True)),
                ('nombres', models.CharField(max_length=255, null=True)),
                ('apellidos', models.CharField(max_length=255, null=True)),
                ('vigenciaOferta', models.PositiveIntegerField(null=True)),
                ('calificacionCliente', models.CharField(max_length=150, null=True)),
                ('indicadorCliente', models.CharField(max_length=150, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('empresa_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaDetalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=255, null=True)),
                ('valorUnitario', models.FloatField(null=True)),
                ('cantidad', models.PositiveIntegerField(null=True)),
                ('precio', models.FloatField(null=True)),
                ('codigo', models.CharField(max_length=255, null=True)),
                ('informacionAdicional', models.TextField(null=True)),
                ('descuento', models.FloatField(null=True)),
                ('impuesto', models.FloatField(null=True)),
                ('valorDescuento', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='mdo_generarOferta.oferta')),
            ],
        ),
    ]
