# Generated by Django 3.1.7 on 2021-09-20 21:46

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('autorizador_id', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(choices=[('supermonedas', 'Supermonedas'), ('credito', 'Credito'), ('pagos', 'Pagos'), ('cobros', 'Cobros'), ('descuentos', 'Descuentos'), ('otro', 'Otro')], default='otro', max_length=255)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('candelado', 'Candelado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=255)),
                ('credito', models.IntegerField(default=0)),
                ('debito', models.IntegerField(default=0)),
                ('saldo', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
