# Generated by Django 3.1.7 on 2021-09-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_monedas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monedas',
            name='empresa_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monedas',
            name='tipo',
            field=models.CharField(choices=[('Supermonedas', 'Supermonedas'), ('Credito', 'Credito'), ('Pagos', 'Pagos'), ('Cobros', 'Cobros'), ('Descuentos', 'Descuentos'), ('Acumulación', 'Acumulacion'), ('Consumo', 'Comsumo'), ('Otro', 'Otro')], default='Otro', max_length=255),
        ),
    ]
