# Generated by Django 3.1.7 on 2022-01-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_monedas', '0002_auto_20210924_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='monedas',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monedas',
            name='fechaVigencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
