# Generated by Django 3.1.7 on 2022-02-23 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionRefil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPredicciones', models.DateField(null=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=13)),
                ('telefono', models.CharField(max_length=250, null=True)),
                ('correo', models.EmailField(max_length=255, null=True)),
                ('cliente', models.SmallIntegerField(null=True)),
                ('negocio', models.SmallIntegerField(null=True)),
                ('total', models.FloatField(null=True)),
                ('empresa_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=150, null=True)),
                ('valorUnitario', models.FloatField(null=True)),
                ('cantidad', models.PositiveIntegerField(null=True)),
                ('precio', models.FloatField(null=True)),
                ('codigo', models.CharField(max_length=250, null=True)),
                ('informacionAdicional', models.TextField(null=True)),
                ('descuento', models.FloatField(null=True)),
                ('impuesto', models.FloatField(null=True)),
                ('valorDescuento', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('prediccionRefil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='mdo_prediccionRefil.prediccionrefil')),
            ],
        ),
    ]
