# Generated by Django 3.1.7 on 2022-02-22 19:42

import apps.MDP.mdp_productos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAvisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.CharField(blank=True, max_length=150, null=True)),
                ('fechaCompra', models.DateTimeField(blank=True, null=True)),
                ('productosVendidos', models.IntegerField(blank=True, null=True)),
                ('precioVenta', models.FloatField(blank=True, null=True)),
                ('alerta', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=150, null=True)),
                ('subCategoria', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigoBarras', models.CharField(blank=True, max_length=150, null=True)),
                ('refil', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('caducidad', models.IntegerField(blank=True, default=0, null=True)),
                ('costoCompra', models.FloatField(blank=True, null=True)),
                ('precioVentaA', models.FloatField(blank=True, null=True)),
                ('precioVentaB', models.FloatField(blank=True, null=True)),
                ('precioVentaC', models.FloatField(blank=True, null=True)),
                ('precioVentaD', models.FloatField(blank=True, null=True)),
                ('precioVentaE', models.FloatField(blank=True, null=True)),
                ('precioVentaBultos', models.FloatField(blank=True, null=True)),
                ('parametrizacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(default='Inactivo', max_length=150, null=True)),
                ('variableRefil', models.CharField(blank=True, max_length=150, null=True)),
                ('lote', models.CharField(blank=True, max_length=150, null=True)),
                ('fechaElaboracion', models.DateField(blank=True, null=True)),
                ('fechaCaducidad', models.DateField(blank=True, null=True)),
                ('empresa_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaUltimaStock', models.DateField(blank=True, null=True)),
                ('montoCompra', models.FloatField(blank=True, null=True)),
                ('empresa_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mdp_productos.productos')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteRotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('diasPeriodo', models.IntegerField(blank=True, null=True)),
                ('productosVendidos', models.IntegerField(blank=True, null=True)),
                ('tipoRotacion', models.CharField(blank=True, max_length=150, null=True)),
                ('montoVenta', models.FloatField(blank=True, null=True)),
                ('empresa_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mdp_productos.productos')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteCaducidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCaducidad', models.DateField(blank=True, null=True)),
                ('productosCaducados', models.IntegerField(blank=True, null=True)),
                ('diasParaCaducar', models.IntegerField(blank=True, null=True)),
                ('empresa_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mdp_productos.productos')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteAbastecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadSugeridaStock', models.IntegerField(blank=True, null=True)),
                ('fechaMaximaStock', models.DateField(blank=True, null=True)),
                ('mostrarAviso', models.SmallIntegerField(default=0)),
                ('notificacionEnviada', models.SmallIntegerField(default=0)),
                ('empresa_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mdp_productos.productos')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.MDP.mdp_productos.models.upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='imagenes', to='mdp_productos.productos')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fechaElaboracion', models.DateField(blank=True, null=True)),
                ('fechaCaducidad', models.DateField(blank=True, null=True)),
                ('precioCompra', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mdp_productos.productos')),
            ],
        ),
    ]
